#
# Copyright (C) 2012 Samsung Electronics
# Lukasz Majewski <l.majewski@samsung.com>
#
# SPDX-License-Identifier:	GPL-2.0+
#

#UBOOTINCLUDE_TEMP = $(UBOOTINCLUDE)

UBOOTINCLUDE	+= -I$(SRCTREE)/board/mediatek/include

obj-y += mtk_cmd.o

#UBOOTINCLUDE := $(UBOOTINCLUDE_TEMP)

#$(warning ====================================================================)
#$(warning $(SRCTREE))
#$(warning $(OBJTREE))
#$(warning $(UBOOTINCLUDE))
#$(warning $(ARCH))
#$(warning $(BOARD))
#$(warning ====================================================================)

