/*
 * Automatically generated by make menuconfig: don't edit
 */
#define AUTOCONF_INCLUDED
#define MT7623 1
#undef  MT7622
#undef  FPGA
#define ASIC 1
#define MT7623_ASIC_BOARD 1
#undef  ON_BOARD_NAND_FLASH_COMPONENT
#undef  ON_BOARD_SPI_FLASH_COMPONENT
#define ON_BOARD_EMMC_COMPONENT 1
#undef  OFF_BOARD_SD_CARD_COMPONENT
#define PDMA_NEW 1
#define RX_SCATTER_GATTER_DMA 1
#define CONFIG_USE_GE1 1
#undef  CONFIG_USE_GE2
#undef  GE_MII_FORCE_100
#undef  GE_RVMII_FORCE_100
#undef  GE_MII_AN
#define GE_RGMII_FORCE_1000 1
#undef  GE_RGMII_AN
#undef  CONFIG_GE1_TRGMII_FORCE_2600
#define MAC_TO_MT7530_MODE 1
#define None 1
#undef  FW_UPGRADE_BY_USB
#undef  FW_UPGRADE_BY_SDXC
#undef  FW_UPGRADE_BY_WEBUI
#undef  DUAL_IMAGE_SUPPORT
